name: pictiknew
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  qr_flutter:
    git:
      url: git://github.com/lukef/qr.flutter.git
      ref: 2.0.0-dev.1
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_svg: ^0.18.0
  shared_preferences: ^0.5.3+4
  progress_dialog: ^1.2.0
  floating_bottom_navigation_bar: ^1.2.0
  google_fonts: ^1.1.0
  carousel_pro: ^1.0.0
  intl: ^0.16.0
  dio: ^3.0.9
  http: ^0.12.0+4
  persistent_bottom_nav_bar: ^1.5.5
  cloud_audio_player: ^0.0.2
  flutter_staggered_grid_view: ^0.3.0
  xml2json: ^4.0.0
  esys_flutter_share: ^1.0.2
  pin_code_text_field: ^1.5.0
  photo_view: ^0.9.0
  transparent_image: ^1.0.0
  fluttertoast: ^3.1.3
  image_picker: ^0.6.3+1
  permission_handler: ^4.0.0
  network_to_file_image: ^2.3.1
  flutter_native_image: ^0.0.4
  audioplayer: ^0.8.1
  path_provider: ^1.6.9
  sliding_up_panel: ^1.0.2
  contacts_service: ^0.4.6
  clay_containers: ^0.2.2
  share: ^0.6.3+4
  carousel_slider: ^1.3.1
  convex_bottom_bar: ^2.6.0
  barcode_scanner: ^1.0.1
  #qr_flutter: ^1.1.1
#  google_maps_flutter: ^0.5.28+1
  image_gallery_saver: ^1.2.2
  flutter_speed_dial: ^1.2.5
  gallery_saver: ^2.0.1
  url_launcher: ^5.1.6
  get_it: ^1.0.3+2
  flutter_windowmanager: ^0.0.1+1
  image_slider: ^1.0.2
  flutter_local_notifications:
  rxdart: any


#  maps_launcher: ^1.2.2+2



dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/whatsapp.png
    - assets/chat.png
    - assets/mail.png
    - images/icon_camera.png
    - images/icon_photoframe1.png
    - images/icon_login.png
    - images/person.png
    - images/icon_logo.png
    - images/om2.png
    - images/dollar.png
    - images/icon_cameranew.png
    - images/icon_selected.png
    #- images/loginback.png
    - images/back3.png
    - images/Back90.png
    - images/back99.png
    - images/back4.png
    #- images/No_photo.png
    - images/connection.png
    - images/pencil.png
    - images/back5.png
    - images/back6.png
    - images/bi2.png
    - images/back7.png
    - images/back8.png
    - images/back14.png
    - images/back10.png
    - images/back12.png
    - images/back13.png
    - images/back15.png
    - images/back16.png
    - images/back17.png
    - images/background.png
    #- images/location1.png
    - images/google-maps.png
    - images/back19.png
    - images/intro5.jpeg
    - images/bi1.png
    - images/icon_pending.png
    - images/icon_allimages.png
    - images/icon_maximize.png
    - images/om.png
    - images/mail.png
    - images/chat.png
    - images/sms.png
    #- images/social.png
    - images/gmail.png
    - images/instagram.png
    - images/earth.png
    - images/logout.png
    - images/back010.png
    - images/back010.png
    - images/back010.png
    - images/back010.png
    - images/back010.png
    - images/back010.png
    - images/back010.png
    - images/twitter.png
    - images/back001.png
    - images/back002.png
    - images/linkedin.png
    - images/instagram.png
    - images/back003.png
    - images/back004.png
    - images/back005.png
    - images/back006.png
    - images/back009.png
    - images/facebook.png
    - images/onlylogo.jpeg
    - assets/10.jpeg
#    - images/7.png
    - images/13.png
    - images/insta_placeholder.png
    - images/no_data.png
    - images/man.png
    - images/whatsapp.png
    - assets/loading.gif
    - images/icon_user.png
    - images/logo.png
    - images/opicxologo.png
    - images/Youtube.png
   # - images/NoImage.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
 # fonts:
   # - family: WorkSans
      #fonts:
      #   - asset: fonts/WorkSans-Black.ttf
         #- asset: fonts/WorkSans-BlackItalic.ttf
        # - asset: fonts/WorkSans-Medium.ttf
         #- asset: fonts/WorkSans-Light.ttf
         #- asset: fonts/WorkSans-MediumItalic.ttf
         #- asset: fonts/WorkSans-SemiBold.ttf
        #   style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
